# ============================================
# Week 3 - Day 5
# Churn + LTV Dashboard
# ============================================

import pandas as pd
import streamlit as st

# Dashboard page configuration
st.set_page_config(
    page_title="Customer Churn & LTV Dashboard",
    page_icon="📊",
    layout="wide"
)

# Dashboard title
st.title("📊 Customer Churn & Lifetime Value Dashboard")

st.write(
    "Interactive dashboard for analyzing customer churn "
    "and predicted Customer Lifetime Value (LTV)."
)
# ============================================
# Load customer dataset
# ============================================

DATA_PATH = "data/initial_engineered_customer_dataset.csv"

df = pd.read_csv(DATA_PATH)

# Show basic dataset information
st.subheader("Customer Dataset")

st.write("Total Customers:", len(df))

st.dataframe(df.head(10))
# ==========================================
# Churn Analysis
# ==========================================

st.subheader("Customer Churn Analysis")

# Count churned and non-churned customers
churn_counts = df["Churn"].value_counts()

# Display churn distribution
st.bar_chart(churn_counts)

# Display exact counts
st.write("Churn Distribution:")
st.dataframe(churn_counts.rename("Customers"))
# ==========================================
# LTV Analysis
# ==========================================

st.subheader("Customer Lifetime Value (LTV) Analysis")

st.write("LTV is based on predicted customer lifetime value.")
st.write("Predicted LTV values generated by the trained Random Forest model.")

# Convert TotalCharges to numeric
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

# Remove missing LTV values
ltv_data = df["TotalCharges"].dropna()

# LTV summary metrics
col1, col2, col3 = st.columns(3)

with col1:
    st.metric("Average LTV", f"${ltv_data.mean():,.2f}")

with col2:
    st.metric("Maximum LTV", f"${ltv_data.max():,.2f}")

with col3:
    st.metric("Minimum LTV", f"${ltv_data.min():,.2f}")

# LTV Distribution
st.write("### LTV Distribution")

st.bar_chart(ltv_data.value_counts().sort_index().head(20))

# LTV statistics
st.write("### LTV Statistics")

ltv_stats = pd.DataFrame({
    "Metric": [
        "Average LTV",
        "Median LTV",
        "Maximum LTV",
        "Minimum LTV"
    ],
    "Value": [
        ltv_data.mean(),
        ltv_data.median(),
        ltv_data.max(),
        ltv_data.min()
    ]
})

st.dataframe(ltv_stats, use_container_width=True)
# ============================================================
# LTV by Churn Status
# ============================================================

st.subheader("LTV by Churn Status")

# Use the same rows that are present in ltv_data
ltv_churn_data = df.loc[ltv_data.index, ["Churn"]].copy()

# Add predicted LTV values
ltv_churn_data["Predicted_LTV"] = ltv_data.values

# Calculate average predicted LTV for each churn status
avg_ltv_by_churn = (
    ltv_churn_data
    .groupby("Churn")["Predicted_LTV"]
    .mean()
    .sort_index()
)

# Display chart
st.bar_chart(avg_ltv_by_churn)

# Display exact values
st.write("Average Predicted LTV by Churn Status")

st.dataframe(
    avg_ltv_by_churn
    .rename("Average LTV")
    .to_frame()
)